# https://www.gitpod.io/docs/41_Config_Gitpod_File/
# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: microsoft/dotnet:latest
# Command to start on workspace startup (optional)
tasks:
  - init: export ASPNETCORE_HTTPS_REDIRECTION_ENABLED=false
  - command: dotnet run --project src/slideshow/slideshow.csproj
  # - command: dotnet test /p:CollectCoverage=true
# Ports to expose on workspace startup (optional)
ports:
  - port: 5000
    onOpen: open-browser
  - port: 5001
    onOpen: ignore