image: microsoft/dotnet:latest

cache:
  paths:
    - tools/
    - packages/

stages:
  - build
  - test

build:
  stage: build
  script:
    - "dotnet build"
  artifacts:
    paths:
      - "**/*/bin"

test:
  stage: test
  script:
    - "[ -d tools/trx2junit ] || dotnet tool install trx2junit --tool-path tools/trx2junit"
    - "dotnet test /p:CollectCoverage=true --results-directory $CI_PROJECT_DIR --logger trx;LogFileName=TestResults.trx"
    # workaround: LogFileName is ignored
    - mv *.trx TestResults.trx
    - "[ -e TestResults.trx ] && ./tools/trx2junit/trx2junit TestResults.trx"
  artifacts:
    paths:
      - results
    reports:
      junit: TestResults.xml