# https://www.gitpod.io/docs/41_Config_Gitpod_File/
# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: microsoft/dotnet:latest
# Command to start on workspace startup (optional)
tasks:
  - init: dotnet build
  - command: dotnet test
  - command: dotnet run --project src/slideshow/slideshow.csproj
# Ports to expose on workspace startup (optional)
ports:
  - port: 5000
    onOpen: open-preview
