# Read more about this feature here: https://docs.gitlab.com/ee/user/project/merge_requests/sast.html
#
# Configure the scanning tool through the environment variables.
# List of the variables: https://gitlab.com/gitlab-org/security-products/sast#settings
# How to set: https://docs.gitlab.com/ee/ci/yaml/#variables

sast:
  stage: test
  image: microsoft/dotnet:latest
  allow_failure: true
  script:
    - for f in src/*/*.csproj ; do dotnet add "$f" package SecurityCodeScan ; done
    - dotnet build --no-incremental /flp:v=q /flp:logfile=msbuild.log
    - dotnet ./tools/dotnet2glsast/dotnet2glsast.dll
  artifacts:
    reports:
      sast: gl-sast-report.json
  dependencies: []
  only:
    refs:
      - branches
    variables:
      - $GITLAB_FEATURES =~ /\bsast\b/
  except:
    variables:
      - $SAST_DISABLED
