// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using slideshow.db;

namespace slideshow.db.sqlite.Migrations
{
    [DbContext(typeof(SqliteSlideshowContext))]
    [Migration("20190622212952_SlideHeaderLength100")]
    partial class SlideHeaderLength100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("slideshow.data.Models.CacheEntry", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("AbsoluteExpiration");

                    b.Property<TimeSpan?>("AbsoluteExpirationRelativeToNow");

                    b.Property<DateTimeOffset?>("CreatedOn");

                    b.Property<DateTimeOffset?>("ModifiedOn");

                    b.Property<TimeSpan?>("SlidingExpiration");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("Key");

                    b.ToTable("CacheEntries");
                });

            modelBuilder.Entity("slideshow.data.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("Order");

                    b.HasKey("SectionId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("slideshow.data.Models.Slide", b =>
                {
                    b.Property<int>("SlideId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("Order");

                    b.Property<int>("SectionId");

                    b.Property<string>("Template");

                    b.HasKey("SlideId");

                    b.HasIndex("SectionId");

                    b.ToTable("Slides");
                });

            modelBuilder.Entity("slideshow.data.Models.Slide", b =>
                {
                    b.HasOne("slideshow.data.Models.Section", "Section")
                        .WithMany("Slides")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
